# Generated by Django 3.2 on 2021-05-12 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('client', models.CharField(max_length=250)),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('thumbnail_image', models.ImageField(upload_to='img/portfolio/')),
                ('full_image', models.ImageField(upload_to='img/portfolio/')),
                ('modal_id', models.CharField(max_length=250)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myportfolioapp.service')),
            ],
        ),
    ]
