# Generated by Django 3.2 on 2021-05-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolioapp', '0002_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='modal_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
