# Generated by Django 3.2 on 2021-05-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolioapp', '0003_service_modal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('eventDate', models.DateField(blank=True, null=True)),
                ('event_title', models.CharField(max_length=200)),
                ('event_details', models.TextField()),
            ],
        ),
    ]
