# Generated by Django 3.2 on 2021-05-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolioapp', '0004_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/about/'),
        ),
    ]
