# Generated by Django 3.2 on 2021-05-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolioapp', '0010_alter_contact_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySocialDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('link', models.URLField(max_length=250)),
                ('icon', models.CharField(max_length=150)),
            ],
        ),
    ]
