# Generated by Django 3.2 on 2021-05-28 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolioapp', '0011_companysocialdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='linkin_link',
            new_name='linkdin_link',
        ),
    ]
